# Generated by Django 5.2.2 on 2025-06-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CAS', 'College of Arts and Science (CAS)'), ('CRIM', 'College of Criminology'), ('CBA', 'College of Business and Accountancy (CBA)'), ('CCS', 'College of Computer Studies (CCS)'), ('CTE', 'College of Teacher Education (CTE)')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_level',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], default='1st Year', max_length=10),
        ),
    ]
