# Generated by Django 5.1.6 on 2025-07-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CAS', 'College of Arts and Science (CAS)'), ('CCJE', 'College of Criminology'), ('CBA', 'College of Business and Accountancy (CBA)'), ('CCS', 'College of Computer Studies (CCS)'), ('CTE', 'College of Teacher Education (CTE)')], default='', max_length=10),
        ),
    ]
