# Generated by Django 5.1.6 on 2025-07-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CAS', 'College of Arts and Science (CAS)'), ('CCJE', 'College of Criminal Justice Education (CCJE)'), ('CBA', 'College of Business and Accountancy (CBA)'), ('CCS', 'College of Computer Studies (CCS)'), ('CTE', 'College of Teacher Education (CTE)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=20),
        ),
    ]
