# Generated by Django 5.2.2 on 2025-07-07 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_course_alter_student_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_admin',
        ),
    ]
