# Generated by Django 5.2.2 on 2025-07-09 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_presencelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencelog',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presencelog',
            name='presence_type',
            field=models.CharField(default='class', max_length=50),
        ),
        migrations.AlterField(
            model_name='presencelog',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
