# Generated by Django 5.2.2 on 2025-07-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_presencelog_edited_presencelog_presence_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presencelog',
            old_name='presence_type',
            new_name='purpose',
        ),
    ]
