# Generated by Django 5.2.2 on 2025-07-10 14:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_rename_presence_type_presencelog_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencelog',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='presencelog',
            name='presence_type',
            field=models.CharField(default='class', max_length=50),
        ),
        migrations.AddField(
            model_name='presencelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presencelog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ArchivedPresenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('date', models.DateField()),
                ('role', models.CharField(default='Student', max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('purpose', models.CharField(default='class', max_length=50)),
                ('presence_type', models.CharField(default='class', max_length=50)),
                ('edited', models.BooleanField(default=False)),
                ('month_archived', models.DateField()),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
            ],
        ),
    ]
