# Generated by Django 5.2.2 on 2025-07-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_presencelog_name_presencelog_presence_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presencelog',
            name='name',
        ),
        migrations.RemoveField(
            model_name='presencelog',
            name='presence_type',
        ),
        migrations.RemoveField(
            model_name='presencelog',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='presencelog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='ArchivedPresenceLog',
        ),
    ]
