# Generated by Django 5.2.2 on 2025-07-11 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_remove_presencelog_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedPresenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('role', models.CharField(default='Student', max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('purpose', models.CharField(default='class', max_length=50)),
                ('edited', models.BooleanField(default=False)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
            ],
        ),
    ]
