# Generated by Django 5.2.2 on 2025-07-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_archivedpresencelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(choices=[('CAS', 'College of Arts and Science (CAS)'), ('CCJE', 'College of Criminal Justice Education (CCJE)'), ('CBA', 'College of Business and Accountancy (CBA)'), ('CCS', 'College of Computer Studies (CCS)'), ('CTE', 'College of Teacher Education (CTE)')], max_length=10)),
                ('course', models.CharField(max_length=100)),
                ('year_level', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], default='1st Year', max_length=10)),
                ('section', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='archived_photos/')),
            ],
        ),
    ]
