# Generated by Django 5.2.2 on 2025-07-13 14:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_archivedstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedpresencelog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='archivedpresencelog',
            name='department',
        ),
        migrations.RemoveField(
            model_name='archivedpresencelog',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='archivedpresencelog',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='archivedpresencelog',
            name='role',
        ),
        migrations.RemoveField(
            model_name='archivedpresencelog',
            name='student',
        ),
        migrations.RemoveField(
            model_name='archivedstudent',
            name='course',
        ),
        migrations.RemoveField(
            model_name='archivedstudent',
            name='department',
        ),
        migrations.RemoveField(
            model_name='archivedstudent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='archivedstudent',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='archivedstudent',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='archivedstudent',
            name='password',
        ),
        migrations.RemoveField(
            model_name='archivedstudent',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='archivedstudent',
            name='section',
        ),
        migrations.RemoveField(
            model_name='archivedstudent',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='archivedstudent',
            name='year_level',
        ),
        migrations.AddField(
            model_name='archivedpresencelog',
            name='archived_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='archivedpresencelog',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.presencelog'),
        ),
        migrations.AddField(
            model_name='archivedstudent',
            name='archived_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='archivedstudent',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student'),
        ),
    ]
