# Generated by Django 5.2.2 on 2025-07-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_student_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencelog',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='guest_snapshots/'),
        ),
    ]
