# Generated by Django 5.2.2 on 2025-08-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_dailysummary_guestlog_monthlysummary_weeklysummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestLog',
        ),
    ]
