# Generated by Django 5.2.2 on 2025-08-05 08:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_delete_guestlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedDataAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DataAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('summary_date', models.DateField()),
                ('student_total', models.IntegerField(default=0)),
                ('guest_total', models.IntegerField(default=0)),
                ('analysis_summary', models.TextField()),
            ],
            options={
                'unique_together': {('summary_type', 'summary_date')},
            },
        ),
        migrations.DeleteModel(
            name='DailySummary',
        ),
        migrations.DeleteModel(
            name='MonthlySummary',
        ),
        migrations.DeleteModel(
            name='WeeklySummary',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year_level',
        ),
        migrations.AddField(
            model_name='archiveddataanalysis',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.dataanalysis'),
        ),
    ]
