# Generated by Django 5.2.2 on 2025-08-13 11:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_archiveddataanalysis_dataanalysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedpresencelog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='archivedpresencelog',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='archivedpresencelog',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archivedpresencelog',
            name='purpose',
            field=models.CharField(blank=True, default='class', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivedpresencelog',
            name='role',
            field=models.CharField(default='Student', max_length=50),
        ),
        migrations.AddField(
            model_name='archivedpresencelog',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student'),
        ),
    ]
