# Generated by Django 5.2.2 on 2025-08-13 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_archivedpresencelog_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedpresencelog',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='archivedpresencelog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='archivedpresencelog',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='archivedpresencelog',
            name='student',
        ),
        migrations.RemoveField(
            model_name='presencelog',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='presencelog',
            name='id',
        ),
        migrations.AddField(
            model_name='archivedpresencelog',
            name='archive_log_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='archivedpresencelog',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='archivedpresencelog',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='archivedpresencelog',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='presencelog',
            name='presence_log_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='presencelog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='presencelog',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
