# Generated by Django 5.2.2 on 2025-08-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_remove_archivedpresencelog_edited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedpresencelog',
            name='archive_log_id',
        ),
        migrations.RemoveField(
            model_name='presencelog',
            name='presence_log_id',
        ),
        migrations.AddField(
            model_name='archivedpresencelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='presencelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
