# Generated by Django 5.2.2 on 2025-08-14 03:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_remove_archivedpresencelog_archive_log_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presencelog',
            old_name='date',
            new_name='logs_timestamp',
        ),
        migrations.RemoveField(
            model_name='archivedpresencelog',
            name='date',
        ),
        migrations.AddField(
            model_name='archivedpresencelog',
            name='logs_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
