# Generated by Django 5.2.2 on 2025-08-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_rename_date_presencelog_logs_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencelog',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
