# Generated by Django 5.2.2 on 2025-08-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_presencelog_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presencelog',
            name='department',
        ),
    ]
