# Generated by Django 5.2.2 on 2025-08-28 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_remove_presencelog_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveddataanalysis',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='dataanalysis',
            name='guest_total',
        ),
        migrations.RemoveField(
            model_name='dataanalysis',
            name='student_total',
        ),
        migrations.AddField(
            model_name='archiveddataanalysis',
            name='analysis_summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='archiveddataanalysis',
            name='summary_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='archiveddataanalysis',
            name='summary_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='analysis_summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='summary_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
