# Generated by Django 5.2.2 on 2025-09-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_remove_archiveddataanalysis_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedstudent',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='archivedstudent',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='archivedstudent',
            name='department',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='archivedstudent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='archivedstudent',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='archivedstudent',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='archivedstudent',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivedstudent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AddField(
            model_name='archivedstudent',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
